// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb2tMtcagTXui1Smes_ZiOpG6ekzk04Cg',
    appId: '1:366315722540:web:c20f73bb653501fa843e89',
    messagingSenderId: '366315722540',
    projectId: 'ac-rental',
    authDomain: 'ac-rental.firebaseapp.com',
    storageBucket: 'ac-rental.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9z3xV-eQx68y8YgSXfTdjJvWpQ2-WMng',
    appId: '1:366315722540:android:eda3cbaac7bb3188843e89',
    messagingSenderId: '366315722540',
    projectId: 'ac-rental',
    storageBucket: 'ac-rental.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN4RkLoKXJQNWGnPKDw4-dpaGda4c0Rbg',
    appId: '1:366315722540:ios:0c793cd9b8c9910d843e89',
    messagingSenderId: '366315722540',
    projectId: 'ac-rental',
    storageBucket: 'ac-rental.firebasestorage.app',
    iosBundleId: 'com.example.acBuy',
  );

}